import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { Player } from '@livepeer/react';
import { Button } from '@material-tailwind/react';

const playbackId = '87b5b3urybkhinp5';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Aprende con 1-2Web3</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Bienvenid@ a <a href="/">1-2Web3</a>
				</h1>
				<div className={styles.videocard}>
					<Player
						title="Waterfalls"
						playbackId={playbackId}
						autoPlay={false}
						muted
						showTitle={false}
						aspectRatio="16to9"
						// poster={<PosterImage />}
						controls={{
							autohide: 3000,
						}}
						theme={{
							borderStyles: { containerBorderStyle: 'hidden' },
							radii: { containerBorderRadius: '10px' },
						}}
						media={{
							sm: '(max-width: 5vw)',
							md: '(max-width: 8vw)',
							lg: '(max-width: 10vw)',
						}}
						objectFit="cover"
					/>
				</div>

				<div className={styles.grid}>
					<Link href="/feed?track=0">
						<div className={styles.card}>
							<h2>Web3 Básico &rarr;</h2>
							<p className={styles.textOverflow}>
								Aprenderás sobre los intangibles, entenderás por qué tienen
								valor en la economía y cómo la tecnología blockchain permite el
								intercambio de valor. Conocerás la historia de la blockchain y
								los criptoactivos.
							</p>
						</div>
					</Link>

					<a href="https://nextjs.org/learn" className={styles.card}>
						<h2>Web3 Intermedio &rarr;</h2>
						<p className={styles.textOverflow}>
							Estudiaremos el trilema de la blockchain (escalabilidad, seguridad
							y descentralización), entenderás qué es la minería, las pruebas de
							trabajo y los nodos descentralizados. Aprenderás a instalar tu
							primera cartera cripto, reconocerás la importancia de la frase
							semilla. Abordaremos los NFT y su importancia.
						</p>
					</a>

					<a
						href="https://github.com/vercel/next.js/tree/canary/examples"
						className={styles.card}
					>
						<h2>Web3 Avanzado &rarr;</h2>
						<p className={styles.textOverflow}>
							Realizarás tus primeras transacciones con la cartera cripo.
							Conocerás el mercado P2B Y P2P y podrás mintear tu primer NFT.
						</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>Web3 Experto &rarr;</h2>
						<p className={styles.textOverflow}>
							Aprenderás sobre los intangibles, entenderás por qué tienen valor
							en la economía y cómo la tecnología blockchain permite el
							intercambio de valor. Conocerás la historia de la blockchain y los
							criptoactivos.
						</p>
					</a>
					<Link href="/team">
						<div className={styles.card}>
							<h2>Equipo &rarr;</h2>
							<p className={styles.textOverflow}>
								Esta iniciativa fue creada bajo ethbogota, conoce al equipo
								detrás de ella.
							</p>
						</div>
					</Link>
				</div>
			</main>

			<footer className={styles.footer}>
				
        <div className="container p-6 text-gray-800">
          <div className="grid lg:grid-cols-2 gap-4">
            <div className="mb-6 md:mb-0">
              <h5 className="font-medium mb-2 uppercase">Footer text</h5>
              <p className="mb-4">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
                aliquam voluptatem veniam, est atque cumque eum delectus sint!
              </p>
            </div>
            <div className="mb-6 md:mb-0">
              <h5 className="font-medium mb-2 uppercase">Footer text</h5>
              <p className="mb-4">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae
                aliquam voluptatem veniam, est atque cumque eum delectus sint!
              </p>
            </div>
          </div>
        </div>
        <div className="text-center text-gray-700 p-4" style={{backgroundColor: 'rgba(0, 0, 0, 0.2)'}}>
		<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					For our ETHGlobal @ ETHbogota community
				
				</a>
        </div>
			</footer>
		</div>
	);
}
