import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { Player } from '@livepeer/react';
import { Button } from "@material-tailwind/react";

const playbackId = '87b5b3urybkhinp5';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Bienvenid@ a <a href="/">ABCrypto</a>
				</h1>
				<div className={styles.videocard}>		
					 <Player
						title="Waterfalls"
						playbackId={playbackId}
						autoPlay
						muted
						showTitle={false}
						aspectRatio="16to9"
						// poster={<PosterImage />}
						controls={{
							autohide: 3000,
						}}
						theme={{
							borderStyles: { containerBorderStyle: 'hidden' },
							radii: { containerBorderRadius: '10px' },
						}}
						media={{
							sm: '(max-width: 5vw)',
							md: '(max-width: 8vw)',
							lg: '(max-width: 10vw)',
						}}
						objectFit='contain'
					/>
				</div>

				<div className={styles.grid}>
					<Link href="/feed?track=0">
						<div className={styles.card}>
							<h2>ABC Básico &rarr;</h2>
							<p>Find in-depth information about Next.js features and API.</p>
						</div>
					</Link>

					<a href="https://nextjs.org/learn" className={styles.card}>
						<h2>ABC Intermedio &rarr;</h2>
						<p>Learn about Next.js in an interactive course with quizzes!</p>
					</a>

					<a
						href="https://github.com/vercel/next.js/tree/canary/examples"
						className={styles.card}
					>
						<h2>ABC Avanzado &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>ABC Experto &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
					<Link href="/team">
						<div className={styles.card}>
							<h2>Equipo &rarr;</h2>
							<p>
								Esta iniciativa fue creada bajo ethbogota, conoce al equipo
								detrás de ella.
							</p>
						</div>
					</Link>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by ETHGlobal @ ETHbogota
				</a>
			</footer>
		</div>
	);
}
